[profile.default]
src = 'src/scalable-dex'
test = 'test/scalable-dex'
script = 'script/scalable-dex'
out = 'out/scalable-dex'
libs = []
ffi = false
chainId = 1
solc = '0.6.12'

[profile.modules]
src = 'src/modules'
test = 'test/modules'
script = 'script/modules'
out = 'out/modules'
libs = ['lib']
solc = '0.8.1'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
